### ISSUE TITLE
Call for Content: ES6

### ISSUE THREAD

**Issue by spacerockzero** [fs-webdev/skill-building-program#23]
The webdevs have been screaming for some ES6 content.
Form a small team or do it alone. Volunteer here!

[See templates](https://github.com/fs-webdev/skill-building-program/tree/master/badge-templates) and [readme](https://github.com/fs-webdev/skill-building-program) for instructions.

**Comment by jamischarles** [comment]
https://github.com/domenic/count-to-6 is really good.
https://github.com/yosuke-furukawa/tower-of-babel may be helpful as well

**Comment by spacerockzero** [comment]
Those look awesome. thanks for the links!

**Comment by spacerockzero** [comment]
We've decided to make ES6 a micro-badge under the V2 JS Journeyman Badge. This way, it can scale for each new year of features more easily, and the set for ES6 isn't big enough for it's own category, anyway.
