### ISSUE TITLE
Content: V2 Web Components

### ISSUE THREAD

**Issue by spacerockzero** [fs-webdev/skill-building-program#25]
The webdevs have been screaming for some Web Components content.
Form a small team or do it alone. Volunteer here!

[See templates](https://github.com/fs-webdev/skill-building-program/tree/master/badge-templates) and [readme](https://github.com/fs-webdev/skill-building-program) for instructions.

**Comment by jshcrowthe** [comment]
I can help with this but right now the thing I'm lacking is time. Also would we want to do this in context with a framework (Polymer) or is this just raw web components?

**Comment by spacerockzero** [comment]
I had figured the long vision was to focus on native web components, and have a microbadge about the additional things that polymer adds, so that people know the difference.

**Comment by dllndv** [comment]
I would like to help by contributing a Polymer microbadge as I learn the framework. Does it make sense to start on that now, or should we wait till the main parts of the Web Components badge are taking shape?

**Comment by spacerockzero** [comment]
A raw outline of topics would be a great start to this

**Comment by jshcrowthe** [comment]
I am going to start on this thing in the `jshcrowthe-v2-webcomponents` branch

**Comment by jshcrowthe** [comment]
The PR for this can be found in #51
