### ISSUE TITLE
Mastery requirements

### ISSUE THREAD

**Issue by lambertsteven** [fs-webdev/skill-building-program#28]
Add more detailed requirements for what can constitute a mastery level project for each category.

Some ideas:

* js - contributing to an open source JS repo a major bug fix or feature
* css - adding csslinting to the orgs workflow, contributing to the Responsive Issues Community Group (RICG)

**Comment by spacerockzero** [comment]
# Master
- Create a project outline. Can also be a real work project.
	- What you wish to build
	- Why it is important
	- How it will benefit our discipline
- Have plan approved by a master in this skill
- Complete your project and present your learning to a gathering of web developers
- Live as legend and mentor for others in this category
