### ISSUE TITLE
Web Components Apprentice badge version

### ISSUE THREAD

**Issue by marybeshaw** [fs-webdev/skill-building-program#69]
The requirement to use Web Components v0 is probably out of date enough that it should either allow someone the option of using v0 or v1 - or just change it to only v1.

**Comment by spacerockzero** [comment]
We should only be using v1 now. Josh was contrib on this. If you could make a PR to that effect, it would serve everybody a lot of good going forward.

**Comment by marybeshaw** [comment]
Will do!

**Comment by marybeshaw** [comment]
Here is the PR for this issue: https://github.com/fs-webdev/skill-building-program/pull/71
