### ISSUE TITLE
Eslinting and Style should at least mention prettier

### ISSUE THREAD

**Issue by joeycozza** [fs-webdev/skill-building-program#78]
[javascript apprentice eslint and style](https://github.com/fs-webdev/skill-building-program/blob/master/badges-active/javascript/_micro_linting-and-js-style-guide.md) should probably ask about/mention prettier.

Some possible questions 
- What makes prettier different from eslint? 
- How can "everything be fixable" with prettier, and not eslint?

I'll get around to making a PR for this soon, I just wanted to make an issue so I won't forget.

**Comment by spacerockzero** [comment]
I agree, prettier wasn’t out when this was written.

**Comment by joeycozza** [comment]
done and done.
