### ISSUE TITLE
Update some copy-pasta for Intro of Module Formats

### ISSUE THREAD

**Issue by joeycozza** [fs-webdev/skill-building-program#79]
[module formats](https://github.com/fs-webdev/skill-building-program/blob/master/badges-active/javascript/_micro_javascript-module-formats.md) has a copy pasted Intro from design patterns. Fix that.

**Comment by spacerockzero** [comment]
The quote is fine. You mean the other part?

**Comment by jamischarles** [comment]
Yep looked good 👍

**Comment by spacerockzero** [comment]
lol Jamis. :unicorn:

**Comment by spacerockzero** [comment]
@joeycozza I get what you mean now, i didn't credit the quote. Fixed in https://github.com/fs-webdev/skill-building-program/commit/fd01dc39c97e5be784824d10f99f81c511d71c15

**Comment by joeycozza** [comment]
No, all of the copy of the Intro section is the exact same from the Design Patterns Skill.

[module formats Intro section](https://github.com/fs-webdev/skill-building-program/blob/master/badges-active/javascript/_micro_javascript-module-formats.md#intro) vs [design patterns Intro section](https://github.com/fs-webdev/skill-building-program/blob/master/badges-active/javascript/_micro_essential-javascript-patterns.md#intro)

I assume that since we are talking about Modules in the module skill, we shouldn't have an introduction talking all about design patterns, especially when the design patterns skill has all of that stuff.

**Comment by spacerockzero** [comment]
oh, i get it now ;)
Prob an oversight in the rush it was written.
hmm. If we could find some better replacement, that would be ideal.

**Comment by joeycozza** [comment]
For sure. When I have a little time, I'll find/write something good for the Intro.

**Comment by spacerockzero** [comment]
how about this? https://github.com/fs-webdev/skill-building-program/pull/80
