### ISSUE TITLE
Broken semver links

### ISSUE THREAD

**Issue by justincy** [fs-webdev/skill-building-program#87]
The first [required semver](https://github.com/fs-webdev/skill-building-program/blob/master/badges-active/frontier/_micro_semver.md#required) link is broken. I'm not sure what's intended there, otherwise I'd submit a PR. The nodesource blog link can be fixed by appending a `/`. I don't know if the semver.org link is supposed to be there as a separate bullet point.

**Comment by spacerockzero** [comment]
that 404 page, tho.
on it.

**Comment by redbugz** [comment]
It was a trailing dash. Fixed
